version: "3.8"

services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm test
    networks:
      - luma-test-network

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres-test
      - REDIS_HOST=redis-test
    command: npm test
    depends_on:
      - postgres-test
      - redis-test
    networks:
      - luma-test-network

  postgres-test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=luma_test
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - luma-test-network

  redis-test:
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    tmpfs:
      - /data
    networks:
      - luma-test-network

  mock-stripe:
    image: stripe/stripe-mock:latest
    ports:
      - "12111:12111"
      - "12112:12112"
    networks:
      - luma-test-network

networks:
  luma-test-network:
    driver: bridge
