name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint:ci

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Security scan placeholder
        run: |
          echo "Security scanning is not configured yet."
          echo "To enable Snyk security scanning, configure the SNYK_TOKEN secret."

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [test, security-scan]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install root dependencies
        run: npm ci
      - name: Install frontend dependencies and verify i18next modules
        run: |
          cd frontend
          npm ci
          # Ensure i18next dependencies are installed
          if [ ! -d "node_modules/i18next" ] || [ ! -d "node_modules/i18next-http-backend" ] || [ ! -d "node_modules/i18next-browser-languagedetector" ]; then
            echo "Installing missing i18next dependencies..."
            npm install i18next i18next-http-backend i18next-browser-languagedetector next-i18next react-i18next
          fi
      - name: Build application
        run: |
          cd frontend
          npm run build
      - name: Deploy to development
        run: echo "Deploy to development environment"
        # Add actual deployment steps here

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [test, security-scan]
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install root dependencies
        run: npm ci
      - name: Install frontend dependencies and verify i18next modules
        run: |
          cd frontend
          npm ci
          # Ensure i18next dependencies are installed
          if [ ! -d "node_modules/i18next" ] || [ ! -d "node_modules/i18next-http-backend" ] || [ ! -d "node_modules/i18next-browser-languagedetector" ]; then
            echo "Installing missing i18next dependencies..."
            npm install i18next i18next-http-backend i18next-browser-languagedetector next-i18next react-i18next
          fi
      - name: Build application
        run: |
          cd frontend
          npm run build
      - name: Deploy to production
        run: echo "Deploy to production environment"
        # Add actual deployment steps here
